### PR TITLE
Added quicksort algorithm. Sorts by ID now.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Roughsketch** [comment]
You don't need any of that. Arrays in JavaScript have a sort method.

```js
XBees.sort(function(a, b) {
    return a.id- b.id;
});
```

**Comment by Roughsketch** [comment]
@drewster87 Can you edit this so I can close this PR? You just need to remove all the quicksort code and copy that snippet I gave you.

**Comment by ghost** [comment]
Why does the algorithm not work?

**Comment by Roughsketch** [comment]
It's not that it doesn't work, it's that it's excessive and not needed. Not to mention that browser implementations use quicksort and merge sort behind the scenes anyway. Also, we're not in a position where we're sorting hundreds of thousands of elements, let alone doing it several times per second, so it's not going to help over the default implementation. I would consider it more if you wrote it, but since it was taken verbatim from a website I don't feel bad scrapping it.

Please remove it and use the default sort implementation instead. For reference, you can use the example I gave above or this ES6 version:

```js
Xbees.sort((a, b) => b.id - a.id)
```

**Comment by ghost** [comment]
K I'll get to it when I get to it.  Probably Sunday which is when I had my
precious free time blocked out for it.

**Comment by ghost** [comment]
K sorry about that response. I'll of course fix it. You keep catching me in
the middle of these massive anxiety attacks when I'm already freaking out.
I plan on working on it this weekend and hopefully finishing up all of it.

**Pull request merged**
